@startuml
'https://plantuml.com/sequence-diagram

!theme bluegray
!pragma teoz true

skinparam backgroundColor #whitesmoke
title States

participant Idle
participant Connecting
participant Connected
participant Configured
participant ReadOnly
participant Reconnecting
participant Closing
participant Closed
participant Error

Idle --> Connecting : connect
Connecting --> Connected : WS opened
Connected --> Configured : SessionResponse(readOnly = false)
Connected --> ReadOnly : SessionResponse(readOnly = true)
Configured --> ReadOnly : Event.ConversationDisconnect && DeploymentConfig.ReadOnly
Configured --> Reconnecting : Network lost
Reconnecting -> Configured : Network reestablished && SessionResponse(readOnly = false)
ReadOnly --> Reconnecting : Network lost
Reconnecting -> ReadOnly : Network reestablished && SessionResponse(readOnly = true)
ReadOnly -> Configured : startNewChat()
ReadOnly --> Error : Unexpected error
Configured --> Error : Unexpected error
Connecting --> Error : Failed to connect
Connected --> Error : Failed to configure session
Reconnecting --> Error : Exhausted reconnection attempts.
Configured --> Closing : disconnect()
ReadOnly --> Closing : disconnect()
Closing --> Closed : WS closed

@enduml
