package com.genesys.cloud.messenger.transport

// Generated by: generate-region.main.kts
// Generated at: 2021-05-07T15:15:30.006125-04:00[America/New_York]

enum class Region(
    val domain: String
) {
    PROD("mypurecloud.com"),
    PROD_EUC1("mypurecloud.de"),
    PROD_EUW1("mypurecloud.ie"),
    PROD_APNE1("mypurecloud.jp"),
    PROD_APSE2("mypurecloud.com.au"),
    PROD_USW2("usw2.pure.cloud"),
    PROD_CAC1("cac1.pure.cloud"),
    PROD_EUW2("euw2.pure.cloud"),
    PROD_APNE2("apne2.pure.cloud"),
    PROD_APS1("aps1.pure.cloud"),
    PROD_SAE1("sae1.pure.cloud"),
    PROD_AFS1("afs1.pure.cloud"),
    FEDRAMP_USE2_CORE("use2.us-gov-pure.cloud")
}
