@startuml
'https://plantuml.com/sequence-diagram

!theme bluegray
!pragma teoz true

skinparam backgroundColor #whitesmoke
title Guest Session Duration

participant App
box TransportSDK #lightcyan
participant MessagingClient
participant SessionDurationHandler
participant HealthCheckProvider
end box
box BackEnd
participant Shyrka
end box

rnote over MessagingClient
  Applies to sessions:
  * both Anonymous and Authenticated
end rnote

rnote over MessagingClient
  Session expiration timer starts/resets on:
  * session updates
  * health check
end rnote

App -> MessagingClient: Configuration(..., **sessionExpirationNoticeInterval = DEFAULT_INTERVAL**)
MessagingClient -> SessionDurationHandler:  updateSessionExpirationNoticeInterval(sessionExpirationNoticeInterval)

App [#999]-> MessagingClient: connect
MessagingClient [#999]--> Shyrka: configureSession
Shyrka [#999]--> MessagingClient: SessionConfigured(..., **durationSeconds, expirationDate**)

MessagingClient -> SessionDurationHandler: scheduleExpiration(durationSeconds, expirationDate)
SessionDurationHandler -> MessagingClient: onSessionDurationChange(durationSeconds)
MessagingClient --> App: eventListener.onEvent(SessionDuration(durationSeconds))
SessionDurationHandler -> SessionDurationHandler: startHealthCheckTimer(expirationDate)

alt startHealthCheckTimer()
    SessionDurationHandler -> SessionDurationHandler: scheduleSessionExpirationNotice(expirationDate)
    rnote over SessionDurationHandler
        Health check schedule
        * Do health check only when there were no interaction for long time
        * start timer for calling health check at 5 minutes + 10 seconds before expirationDate
    end rnote
    SessionDurationHandler -> SessionDurationHandler: onHealthCheckTimerExpired()
    SessionDurationHandler --> MessagingClient: startHealthCheck()
    MessagingClient [#999]--> Shyrka: sendHealthCheck()
    Shyrka [#999]--> MessagingClient: Health check response \n(StructuredMessage(metadata = {**sessionDuration =..., expirationDate=;;;})**)
    rnote over MessagingClient
        New values in health check response:
        * durationSeconds (no supposed to change)
        * expirationDate
    end rnote
    MessagingClient -> SessionDurationHandler: scheduleExpiration(durationSeconds, expirationDate)
    alt The new expiration date is fresher
        SessionDurationHandler -> SessionDurationHandler: stopExpirationTimer()
        SessionDurationHandler -> SessionDurationHandler: startExpirationTimer
        SessionDurationHandler -> SessionDurationHandler: startHealthCheckTimer()
    else Expiration date remains the same
        rnote over SessionDurationHandler
            Timer continues until 5 minutes before expiration date
        end rnote
        SessionDurationHandler -> SessionDurationHandler: onTimerExpired()
        SessionDurationHandler --> MessagingClient: onSessionExpirationNotice()
        MessagingClient -> App: eventListener.onEvent(SessionExpirationNotice)
    end
end

alt Any new message after the timer end starts new timer
    Shyrka --> MessagingClient: onMessage
    MessagingClient -> SessionDurationHandler: checkExpiration()
    rnote over SessionDurationHandler
      Given: session expiration notice is sent but we are before the timeout
    end rnote
    SessionDurationHandler --> MessagingClient: onRemoveExpirationNotice
    MessagingClient -> App: eventListener.onEvent(RemoveSessionExpirationNotice)
    rnote over SessionDurationHandler
      Run health check
    end rnote
    SessionDurationHandler -> SessionDurationHandler: startExpirationTimer
    SessionDurationHandler -> SessionDurationHandler: startHealthCheckTimer()
    rnote over SessionDurationHandler
      New timer started
    end rnote
end

alt Clear Conversation
    Shyrka [#999]--> MessagingClient: Clear Conversation
    MessagingClient [#999]-> MessagingClient: invalidateConversationCache()
    Me0ssagingClient [#999]--> App: eventListener.onEvent(Event.ConversationCleared)
end
@enduml