@startuml
'https://plantuml.com/sequence-diagram

!theme bluegray
!pragma teoz true
!include authorization_code_flow.puml

skinparam backgroundColor #whitesmoke
title Authenticated Session

participant App
participant "Auth Server"
participant "Transport SDK"
participant "Genesys Cloud Platform API"
participant "Shyrka API"
participant Agent


autonumber 12
group Transport SDK Auth Flow
    App -> "Transport SDK" : connectAuthenticatedSession()
    "Transport SDK" -> "Shyrka API" : Open websocket.
    "Shyrka API" --> "Transport SDK" : Socket opened.
    "Transport SDK" -> "Shyrka API" : Send ConfigureAuthenticatedSession request.
    "Shyrka API" -> "Shyrka API" : Check JWT validity.
    "Shyrka API" -> "Auth Server" : Check session is still valid at the authentication server.
    "Auth Server" --> "Shyrka API" : Valid session passed.
    "Shyrka API" --> "Transport SDK" : Send successful SessionResponse.
    "Transport SDK" -> App : Notify with MessagingClient.State = State.Configured
    App -> "Transport SDK" : Send message.
    "Transport SDK" -> "Shyrka API" : Send message.
    "Shyrka API" -> "Shyrka API" : Enrich with identity information.
    "Shyrka API" -> Agent : Send message with ID.
end


@enduml
