@startuml
'https://plantuml.com/sequence-diagram

!theme bluegray
!pragma teoz true

skinparam backgroundColor #whitesmoke
title Transport Auth Logout Flow

participant App
participant MessagingClient
participant AuthHandler
participant WebMessagingAPI
participant Shyrka
participant "Genesys Cloud Platform API"


    App -> MessagingClient : 1. logoutFromAuthenticatedSession()
    MessagingClient -> AuthHandler : 2. logoutFromAuthenticatedSession()
    AuthHandler -> WebMessagingAPI : 3. logoutFromAuthenticatedSession()
    WebMessagingAPI -> "Genesys Cloud Platform API" : 4. logoutFromAuthenticatedSession()
    alt #aaff8833 logout success
    Shyrka --> MessagingClient : 5. Event.Logout
    MessagingClient --> App : 6. eventListener(Event.Logout)
    MessagingClient -> MessagingClient: 7. disconnect()
    MessagingClient --> App : 8. onStateChanged(State.Closed)
    else #fcfcfcaa logout failure errorCode == 401
                AuthHandler -> WebMessagingAPI : 9. refreshToken(authHandler.refreshToken)
                alt #aaff8833 refreshToken() success
                WebMessagingAPI --> AuthHandler : 10. success(jwt)
                AuthHandler -> AuthHandler : 11. update jwt.
                AuthHandler -> WebMessagingAPI : 12. logoutFromAuthenticatedSession()
                else #ffaaff33 refreshToken() failure
                WebMessagingAPI --> AuthHandler : 10a. failure
                AuthHandler -> AuthHandler : 11a. clear() jwt and refreshToken from storage.
                AuthHandler --> MessagingClient : 12a. failure
                MessagingClient --> App : 13a. onEvent(Error(AuthLogoutFailed, message, ReAuthenticate))
                end
            else #ffaaff33 errorCode != 401
                MessagingClient --> App : 9a. onEvent(Error(AuthLogoutFailed, message, ReAuthenticate))
    end

@enduml
