@startuml
'https://plantuml.com/sequence-diagram

!theme bluegray
!pragma teoz true

skinparam backgroundColor #whitesmoke
title Transport Auth Flow

participant App
participant MessagingClient
participant AuthHandler
participant WebMessagingAPI
participant Shyrka
participant "Genesys Cloud Platform API"
participant Agent

App -> MessagingClient : 1. authorize(authCode, redirectUri, codeVerifier)
MessagingClient -> AuthHandler : 2. authorize(authCode, redirectUri, codeVerifier)
AuthHandler -> WebMessagingAPI : 3. fetchAuthJwt(authCode, redirectUri, codeVerifier)
WebMessagingAPI -> "Genesys Cloud Platform API" : 4. authCode to jwt exchange.
alt #aaff8833 success fetchAuthJwt
    "Genesys Cloud Platform API" --> WebMessagingAPI : 5. return Jwt and RefreshToken
    WebMessagingAPI --> AuthHandler : 6. return Jwt and RefreshToken
    AuthHandler -> AuthHandler : 7. store refreshToken
    AuthHandler --> App : 8. onEvent(Event.Authorized)
else #ffaaff33 failure
    "Genesys Cloud Platform API" --> WebMessagingAPI : 5a. Failure
    WebMessagingAPI --> AuthHandler : 6a. Failure
    AuthHandler --> App : 7a. onEvent(Error(AuthFailed, message, ReAuthenticate))
end

App -> MessagingClient : 9. connectAuthenticatedSession()
MessagingClient -> Shyrka : 10. connect()
MessagingClient --> App : 11. onStateChanged(State.Connecting)
Shyrka --> MessagingClient : 12. onWebSocketOpened()
MessagingClient --> App : 13. onStateChanged(State.Connected)
MessagingClient -> Shyrka : 14. ConfigureAuthenticatedSession(authHandler.jwt)
Shyrka --> MessagingClient : 15. SessionResponse
     alt #aaff8833 Session response failure. errorCode == 401
            MessagingClient -> AuthHandler : 15a. refreshToken()
            AuthHandler -> WebMessagingAPI : 15b. refreshToken(authHandler.refreshToken)
            alt #aaff8833 refreshToken() success
            WebMessagingAPI --> AuthHandler : 15d. success(jwt)
            AuthHandler -> AuthHandler : 15e. update jwt with refreshed jwt.
            MessagingClient -> Shyrka : 15f. ConfigureAuthenticatedSession(authHandler.jwt)
            Shyrka --> MessagingClient : 15g. SessionResponse
            else #ffaaff33 refreshToken() failure
            WebMessagingAPI --> AuthHandler : 15h. failure
            AuthHandler -> AuthHandler : 15i. clear() jwt and refreshToken from storage.
            AuthHandler --> MessagingClient : 15j. failure
            MessagingClient --> App : 15k. onStateChanged(State.Error(errorCode, message))
            end
        else #ffaaff33 errorCode != 401
            MessagingClient --> App : 15c. onStateChanged(State.Error(errorCode, message))
        end

    MessagingClient --> App : 16. onStateChanged(State.Configured)
    App -> MessagingClient : 17. sendMessage("Hello")
    MessagingClient -> Shyrka : 18. sendMessage("Hello")
    Shyrka -> Shyrka : 19. Enrich with identity information.
    Shyrka -> Agent : 20. sendMessage("Hello") with ID.

@enduml
